// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxwfmrccjrbejqxmmxrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4d2ZtcmNjanJiZWpxeG1teHJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MTE0NjQsImV4cCI6MjA2NDQ4NzQ2NH0.1niwsBD8HBdTDRZ8bzURu1bIN48jIQaijcdWrVC33tQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);